// <auto-generated />
namespace Ownorent.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class capturemorepaypalinfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(capturemorepaypalinfo));
        
        string IMigrationMetadata.Id
        {
            get { return "202006131818434_capture more paypal info"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
