// <auto-generated />
namespace Ownorent.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class cartupdatetohandlerentandrenttoown : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cartupdatetohandlerentandrenttoown));
        
        string IMigrationMetadata.Id
        {
            get { return "202006092030548_cart update to handle rent and rent to own"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
