// <auto-generated />
namespace Ownorent.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class computenumberofdaysuponaddtocartrentandsavetodb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(computenumberofdaysuponaddtocartrentandsavetodb));
        
        string IMigrationMetadata.Id
        {
            get { return "202006100528253_compute number of days upon add to cart rent and save to db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
