// <auto-generated />
namespace Ownorent.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class rentnumberofdays : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rentnumberofdays));
        
        string IMigrationMetadata.Id
        {
            get { return "202006130831470_rent number of days"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
