// <auto-generated />
namespace Ownorent.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class paymentdescriptionpropertytoindicatewhatmonth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(paymentdescriptionpropertytoindicatewhatmonth));
        
        string IMigrationMetadata.Id
        {
            get { return "202006140704569_payment description property to indicate what month"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
